ACCESS_PERMISSION_CATALOG: list[tuple[str, str, str]] = [
    ("dashboard.view", "Visualizar dashboard", "Permite abrir a tela principal de dashboard."),
    ("instances.view", "Visualizar instâncias", "Permite abrir a tela de instâncias."),
    ("instances.manage", "Gerenciar instâncias", "Permite criar, editar e operar instâncias."),
    ("groups.view", "Visualizar grupos de instâncias", "Permite abrir a tela de grupos de instâncias."),
    ("groups.manage", "Gerenciar grupos de instâncias", "Permite criar, editar e excluir grupos de instâncias."),
    ("schedules.view", "Visualizar agendamentos", "Permite abrir a tela de agendamentos."),
    ("schedules.manage", "Gerenciar agendamentos", "Permite criar, editar e excluir agendamentos."),
    ("compartments.view", "Visualizar compartimentos", "Permite abrir a tela de compartimentos."),
    ("compartments.manage", "Gerenciar compartimentos", "Permite sincronizar e importar compartimentos."),
    ("deskmanager.view", "Visualizar DeskManager", "Permite abrir a área do DeskManager."),
    ("deskmanager.create_ticket", "Abrir chamados no DeskManager", "Permite criar chamados no DeskManager."),
    ("reports.view", "Visualizar relatórios", "Permite abrir a tela de relatórios."),
    ("audit.executions.view", "Visualizar auditoria de execuções", "Permite abrir a auditoria de execuções."),
    ("audit.access.view", "Visualizar auditoria de acessos", "Permite abrir a auditoria de acessos."),
    ("audit.settings.view", "Visualizar auditoria de configurações", "Permite abrir a auditoria de configurações."),
    ("admin.view", "Visualizar administração", "Permite visualizar a área administrativa."),
    ("admin.users.view", "Visualizar usuários", "Permite abrir a tela de usuários."),
    ("admin.users.manage", "Gerenciar usuários", "Permite criar e editar usuários."),
    ("admin.access_groups.view", "Visualizar grupos de acesso", "Permite abrir a tela de grupos de acesso."),
    ("admin.access_groups.manage", "Criar/Editar grupos de acesso", "Permite criar e editar grupos de acesso."),
    ("admin.permissions.view", "Visualizar permissões diretas", "Permite visualizar a tabela de permissões diretas."),
    ("admin.permissions.manage", "Gerenciar permissões diretas", "Permite editar label e descrição das permissões."),
]
