DESKMANAGER_USERS: list[tuple[str, str]] = [
    ("2572", "Eduardo"),
    ("835", "Bruno Vieira"),
    ("2057", "Rafaell"),
    ("853", "Judson"),
    ("2531", "Saulo"),
]

DESKMANAGER_CATEGORIES: list[tuple[str, str]] = [
    ("9679", "Docnix Infra/SRE - Ambientes - Atualização"),
    ("9889", "Docnix Infra/SRE - Ambientes - Atualização/Ajuste de Licenças"),
    ("9678", "Docnix Infra/SRE - Ambientes - Configuração (HMG/PRD/DEV)"),
    ("9676", "Docnix Infra/SRE - Ambientes - Criação de Ambiente"),
    ("9677", "Docnix Infra/SRE - Ambientes - Nova Instalação"),
    ("9680", "Docnix Infra/SRE - Ambientes - Replicação / Equiparação"),
    ("9704", "Docnix Infra/SRE - Atividades Interna - Documentação"),
    ("9705", "Docnix Infra/SRE - Atividades Interna - Estudos Técnico"),
    ("9703", "Docnix Infra/SRE - Atividades Interna - Planejamento"),
    ("9702", "Docnix Infra/SRE - Atividades Interna - Reunião Interna"),
    ("9701", "Docnix Infra/SRE - Atividades Interna - Treinamentos"),
    ("9706", "Docnix Infra/SRE - Atividades Interna - Workshops Internos"),
    ("9687", "Docnix Infra/SRE - Backup e Restore - Execução de Backup"),
    ("9688", "Docnix Infra/SRE - Backup e Restore - Falha de Backup"),
    ("9689", "Docnix Infra/SRE - Backup e Restore - Restore"),
    ("9686", "Docnix Infra/SRE - Disponibilidade e Performance - Conexões / Falha de Rede"),
    ("9683", "Docnix Infra/SRE - Disponibilidade e Performance - Indisponibilidade"),
    ("9684", "Docnix Infra/SRE - Disponibilidade e Performance - Lentidão"),
    ("9685", "Docnix Infra/SRE - Disponibilidade e Performance - Upgrade"),
    ("9707", "Docnix Infra/SRE - Infraestrutura - Manutenção de Servidor"),
    ("9708", "Docnix Infra/SRE - Infraestrutura - Migração de Banco de Dados"),
    ("9681", "Docnix Infra/SRE - Infraestrutura - Migração de Servidor"),
    ("9682", "Docnix Infra/SRE - Infraestrutura - Otimização / Ajustes de Servidor"),
    ("9694", "Docnix Infra/SRE - Integrações - API"),
    ("9697", "Docnix Infra/SRE - Integrações - Serviços Externos"),
    ("9695", "Docnix Infra/SRE - Integrações - SMTP / E-mail de Serviço"),
    ("9693", "Docnix Infra/SRE - Integrações - SSO (AD / ADFS / LDAP / SAML)"),
    ("9698", "Docnix Infra/SRE - Operações Técnicas - Automação"),
    ("9700", "Docnix Infra/SRE - Operações Técnicas - Dúvidas Técnicas"),
    ("9696", "Docnix Infra/SRE - Operações Técnicas - Execução de Scripts"),
    ("9699", "Docnix Infra/SRE - Operações Técnicas - Suporte Técnico"),
    ("9692", "Docnix Infra/SRE - Segurança - Certificado SSL"),
    ("9691", "Docnix Infra/SRE - Segurança - Firewall / Whitelist / IPs"),
    ("9690", "Docnix Infra/SRE - Segurança - Relatórios de Vulnerabilidades"),
    ("9666", "Docnix Infra/SRE - TI Interna - Bloqueio de Acessos"),
    ("9665", "Docnix Infra/SRE - TI Interna - Criação de Acesso"),
    ("9669", "Docnix Infra/SRE - TI Interna - Dúvidas"),
    ("9667", "Docnix Infra/SRE - TI Interna - E-mail"),
    ("9672", "Docnix Infra/SRE - TI Interna - Impressora"),
    ("9674", "Docnix Infra/SRE - TI Interna - Internet Lenta"),
    ("9673", "Docnix Infra/SRE - TI Interna - Mouse / Teclado / Headset"),
    ("9671", "Docnix Infra/SRE - TI Interna - Notebook"),
    ("9670", "Docnix Infra/SRE - TI Interna - Suporte"),
    ("9668", "Docnix Infra/SRE - TI Interna - VPN"),
    ("9675", "Docnix Infra/SRE - TI Interna - Wi-Fi"),
    ("9130", "Fábrica de Software - N2 - Atualização"),
    ("9132", "Fábrica de Software - N2 - Backup"),
    ("9128", "Fábrica de Software - N2 - Call"),
    ("9131", "Fábrica de Software - N2 - Cotação"),
    ("9133", "Fábrica de Software - N2 - Criação de ambiente"),
    ("9135", "Fábrica de Software - N2 - Indisponibilidade"),
    ("9136", "Fábrica de Software - N2 - Lentidão"),
    ("9137", "Fábrica de Software - N2 - Logs"),
    ("9134", "Fábrica de Software - N2 - Migração"),
    ("9143", "Fábrica de Software - N2 - Suporte"),
    ("8962", "Grupo ITSS - N2 - Backup - Configuração"),
    ("8951", "Grupo ITSS - N2 - Backup - Copia Backup"),
    ("8958", "Grupo ITSS - N2 - Backup - Criar Backup"),
    ("8953", "Grupo ITSS - N2 - Backup - Restauração"),
    ("8938", "Grupo ITSS - N2 - E-mail - Criação"),
    ("8939", "Grupo ITSS - N2 - E-mail - Licença"),
    ("8936", "Grupo ITSS - N2 - E-mail - Reset senha"),
    ("8942", "Grupo ITSS - N2 - E-mail - Suporte"),
    ("8957", "Grupo ITSS - N2 - Hardware - Mouse / Teclado / Headset"),
    ("8956", "Grupo ITSS - N2 - Hardware - Notebook"),
    ("8965", "Grupo ITSS - N2 - Hardware - Servidor / Serviços"),
    ("8960", "Grupo ITSS - N2 - Hardware - Suporte"),
    ("8946", "Grupo ITSS - N2 - Impressora - Instalação"),
    ("8943", "Grupo ITSS - N2 - Impressora - Suporte"),
    ("9374", "Grupo ITSS - N2 - Melhorias"),
    ("9375", "Grupo ITSS - N2 - Preventiva"),
    ("8961", "Grupo ITSS - N2 - Redes - Cabeada"),
    ("8966", "Grupo ITSS - N2 - Redes - Internet"),
    ("8973", "Grupo ITSS - N2 - Redes - Lentidão"),
    ("8964", "Grupo ITSS - N2 - Redes - Suporte"),
    ("8963", "Grupo ITSS - N2 - Redes - Wi-Fi"),
    ("8944", "Grupo ITSS - N2 - Servidor - Criação de ambiente"),
    ("8950", "Grupo ITSS - N2 - Servidor - Exclusão de ambiente"),
    ("8947", "Grupo ITSS - N2 - Servidor - Manutenção de ambiente"),
    ("8948", "Grupo ITSS - N2 - Servidor - Suporte"),
    ("8952", "Grupo ITSS - N2 - Servidor - Upgrade"),
    ("8955", "Grupo ITSS - N2 - Sistemas - Bloqueio de Acessos"),
    ("8954", "Grupo ITSS - N2 - Sistemas - Criação de Acessos"),
    ("8959", "Grupo ITSS - N2 - Sistemas - Logs"),
    ("8949", "Grupo ITSS - N2 - Sistemas - Suporte"),
    ("8934", "Grupo ITSS - N2 - Telefonia - Celular"),
    ("8935", "Grupo ITSS - N2 - Telefonia - Ramal"),
    ("8937", "Grupo ITSS - N2 - Telefonia - Suporte"),
    ("8945", "Grupo ITSS - N2 - VPN - Criação"),
    ("8941", "Grupo ITSS - N2 - VPN - Exclusão"),
    ("8940", "Grupo ITSS - N2 - VPN - Suporte"),
    ("9120", "ITSS ME - N2 - Backup"),
    ("9123", "ITSS ME - N2 - Call"),
    ("9122", "ITSS ME - N2 - Criação de ambiente"),
    ("9121", "ITSS ME - N2 - Indisponibilidade"),
    ("9125", "ITSS ME - N2 - Logs"),
    ("9129", "ITSS ME - N2 - Suporte"),
    ("9898", "PAS - Configuração DNS"),
    ("9897", "PAS - Criação/desativação de acesso"),
    ("9890", "PAS - Erro de pipeline"),
    ("9891", "PAS - Indisponibilidade"),
    ("9895", "PAS - Logs"),
    ("9892", "PAS - Melhorias"),
    ("9894", "PAS - Migração"),
    ("9893", "PAS - Suporte"),
    ("9896", "PAS - VPN"),
    ("8977", "PM RUN - N2 - Atualização"),
    ("8980", "PM RUN - N2 - Backup"),
    ("8983", "PM RUN - N2 - Call"),
    ("8984", "PM RUN - N2 - Cotação"),
    ("8985", "PM RUN - N2 - Criação de ambiente"),
    ("8982", "PM RUN - N2 - Indisponibilidade"),
    ("8988", "PM RUN - N2 - Lentidão"),
    ("8989", "PM RUN - N2 - Logs"),
    ("8986", "PM RUN - N2 - Migração"),
    ("8992", "PM RUN - N2 - Suporte"),
    ("8993", "PM RUN - N2 - VPN"),
]
